//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketAkhmerova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupermarketEntities : DbContext
    {
        private static SupermarketEntities _context;

        public static SupermarketEntities GetContext()
        {
            if (_context == null)
            {
                _context = new SupermarketEntities();
            }
            return _context;
        }
        public SupermarketEntities()
            : base("name=SupermarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Отделы> Отделы { get; set; }
        public virtual DbSet<Продажи_товаров> Продажи_товаров { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
