//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketAkhmerova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи_товаров
    {
        public int Номер_продажи { get; set; }
        public int Сотрудник { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время { get; set; }
        public int Кол_во { get; set; }
        public int Товар { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Товары Товары { get; set; }
        public double Сумма
        {
            get
            {
                return (double)(Товары.Цена * Кол_во);
            }
        }
    }
}
