//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketAkhmerova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Продажи_товаров = new HashSet<Продажи_товаров>();
        }
    
        public int Номер_товара { get; set; }
        public string Название_товара { get; set; }
        public int Отдел { get; set; }
        public string Страна_производитель { get; set; }
        public string Условия_хранения { get; set; }
        public string Сроки_хранения { get; set; }
        public decimal Цена { get; set; }
        public string Фото_Товары { get; set; }

        public string Отдел_строчный
        {
            get
            {
                return Отделы.Название_отдела;
            }
        }

        public virtual Отделы Отделы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи_товаров> Продажи_товаров { get; set; }
    }
}
